---
# Default Kibana configuration from kibana-docker.

server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200
elasticsearch.username: metricbeat_anonymous_user
#elasticsearch.password: ""
xpack.monitoring.ui.container.elasticsearch.enabled: true
